// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"

	routing "github.com/alanwade2001/go-sepa-infra/routing"
)

// IDocument is an autogenerated mock type for the IDocument type
type IDocument struct {
	mock.Mock
}

// PostDocument provides a mock function with given fields: c
func (_m *IDocument) PostDocument(c *gin.Context) {
	_m.Called(c)
}

// Register provides a mock function with given fields: r
func (_m *IDocument) Register(r *routing.Router) {
	_m.Called(r)
}

// NewIDocument creates a new instance of IDocument. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIDocument(t interface {
	mock.TestingT
	Cleanup(func())
}) *IDocument {
	mock := &IDocument{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
