// Code generated by mockery v2.52.3. DO NOT EDIT.

package service

import (
	data "github.com/alanwade2001/go-sepa-portal/internal/data"
	mock "github.com/stretchr/testify/mock"
)

// MockIStore is an autogenerated mock type for the IStore type
type MockIStore struct {
	mock.Mock
}

type MockIStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIStore) EXPECT() *MockIStore_Expecter {
	return &MockIStore_Expecter{mock: &_m.Mock}
}

// StoreDocument provides a mock function with given fields: content
func (_m *MockIStore) StoreDocument(content string) (*data.Document, error) {
	ret := _m.Called(content)

	if len(ret) == 0 {
		panic("no return value specified for StoreDocument")
	}

	var r0 *data.Document
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*data.Document, error)); ok {
		return rf(content)
	}
	if rf, ok := ret.Get(0).(func(string) *data.Document); ok {
		r0 = rf(content)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*data.Document)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(content)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIStore_StoreDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreDocument'
type MockIStore_StoreDocument_Call struct {
	*mock.Call
}

// StoreDocument is a helper method to define mock.On call
//   - content string
func (_e *MockIStore_Expecter) StoreDocument(content interface{}) *MockIStore_StoreDocument_Call {
	return &MockIStore_StoreDocument_Call{Call: _e.mock.On("StoreDocument", content)}
}

func (_c *MockIStore_StoreDocument_Call) Run(run func(content string)) *MockIStore_StoreDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIStore_StoreDocument_Call) Return(doc *data.Document, err error) *MockIStore_StoreDocument_Call {
	_c.Call.Return(doc, err)
	return _c
}

func (_c *MockIStore_StoreDocument_Call) RunAndReturn(run func(string) (*data.Document, error)) *MockIStore_StoreDocument_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIStore creates a new instance of MockIStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIStore {
	mock := &MockIStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
