// Code generated by mockery v2.52.3. DO NOT EDIT.

package service

import mock "github.com/stretchr/testify/mock"

// MockMessageSender is an autogenerated mock type for the MessageSender type
type MockMessageSender struct {
	mock.Mock
}

type MockMessageSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessageSender) EXPECT() *MockMessageSender_Expecter {
	return &MockMessageSender_Expecter{mock: &_m.Mock}
}

// Send provides a mock function with given fields: v
func (_m *MockMessageSender) Send(v interface{}) error {
	ret := _m.Called(v)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMessageSender_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockMessageSender_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - v interface{}
func (_e *MockMessageSender_Expecter) Send(v interface{}) *MockMessageSender_Send_Call {
	return &MockMessageSender_Send_Call{Call: _e.mock.On("Send", v)}
}

func (_c *MockMessageSender_Send_Call) Run(run func(v interface{})) *MockMessageSender_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *MockMessageSender_Send_Call) Return(_a0 error) *MockMessageSender_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMessageSender_Send_Call) RunAndReturn(run func(interface{}) error) *MockMessageSender_Send_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMessageSender creates a new instance of MockMessageSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessageSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessageSender {
	mock := &MockMessageSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
