// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	entity "github.com/alanwade2001/go-sepa-portal/internal/repository/entity"
	mock "github.com/stretchr/testify/mock"
)

// IInitiation is an autogenerated mock type for the IInitiation type
type IInitiation struct {
	mock.Mock
}

// FindAll provides a mock function with no fields
func (_m *IInitiation) FindAll() ([]*entity.Initiation, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*entity.Initiation
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*entity.Initiation, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*entity.Initiation); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Initiation)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: id
func (_m *IInitiation) FindByID(id string) (*entity.Initiation, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.Initiation
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entity.Initiation, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *entity.Initiation); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Initiation)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Perist provides a mock function with given fields: initn
func (_m *IInitiation) Perist(initn *entity.Initiation) (*entity.Initiation, error) {
	ret := _m.Called(initn)

	if len(ret) == 0 {
		panic("no return value specified for Perist")
	}

	var r0 *entity.Initiation
	var r1 error
	if rf, ok := ret.Get(0).(func(*entity.Initiation) (*entity.Initiation, error)); ok {
		return rf(initn)
	}
	if rf, ok := ret.Get(0).(func(*entity.Initiation) *entity.Initiation); ok {
		r0 = rf(initn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Initiation)
		}
	}

	if rf, ok := ret.Get(1).(func(*entity.Initiation) error); ok {
		r1 = rf(initn)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIInitiation creates a new instance of IInitiation. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIInitiation(t interface {
	mock.TestingT
	Cleanup(func())
}) *IInitiation {
	mock := &IInitiation{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
