// Code generated by mockery v2.52.3. DO NOT EDIT.

package repository

import (
	data "github.com/alanwade2001/go-sepa-portal/internal/data"
	mock "github.com/stretchr/testify/mock"
)

// MockIInitiation is an autogenerated mock type for the IInitiation type
type MockIInitiation struct {
	mock.Mock
}

type MockIInitiation_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIInitiation) EXPECT() *MockIInitiation_Expecter {
	return &MockIInitiation_Expecter{mock: &_m.Mock}
}

// FindAll provides a mock function with no fields
func (_m *MockIInitiation) FindAll() ([]*data.Initiation, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*data.Initiation
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*data.Initiation, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*data.Initiation); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*data.Initiation)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIInitiation_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockIInitiation_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
func (_e *MockIInitiation_Expecter) FindAll() *MockIInitiation_FindAll_Call {
	return &MockIInitiation_FindAll_Call{Call: _e.mock.On("FindAll")}
}

func (_c *MockIInitiation_FindAll_Call) Run(run func()) *MockIInitiation_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIInitiation_FindAll_Call) Return(_a0 []*data.Initiation, _a1 error) *MockIInitiation_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIInitiation_FindAll_Call) RunAndReturn(run func() ([]*data.Initiation, error)) *MockIInitiation_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: id
func (_m *MockIInitiation) FindByID(id string) (*data.Initiation, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *data.Initiation
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*data.Initiation, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *data.Initiation); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*data.Initiation)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIInitiation_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockIInitiation_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id string
func (_e *MockIInitiation_Expecter) FindByID(id interface{}) *MockIInitiation_FindByID_Call {
	return &MockIInitiation_FindByID_Call{Call: _e.mock.On("FindByID", id)}
}

func (_c *MockIInitiation_FindByID_Call) Run(run func(id string)) *MockIInitiation_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIInitiation_FindByID_Call) Return(_a0 *data.Initiation, _a1 error) *MockIInitiation_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIInitiation_FindByID_Call) RunAndReturn(run func(string) (*data.Initiation, error)) *MockIInitiation_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Persist provides a mock function with given fields: initn
func (_m *MockIInitiation) Persist(initn *data.Initiation) (*data.Initiation, error) {
	ret := _m.Called(initn)

	if len(ret) == 0 {
		panic("no return value specified for Persist")
	}

	var r0 *data.Initiation
	var r1 error
	if rf, ok := ret.Get(0).(func(*data.Initiation) (*data.Initiation, error)); ok {
		return rf(initn)
	}
	if rf, ok := ret.Get(0).(func(*data.Initiation) *data.Initiation); ok {
		r0 = rf(initn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*data.Initiation)
		}
	}

	if rf, ok := ret.Get(1).(func(*data.Initiation) error); ok {
		r1 = rf(initn)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIInitiation_Persist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Persist'
type MockIInitiation_Persist_Call struct {
	*mock.Call
}

// Persist is a helper method to define mock.On call
//   - initn *data.Initiation
func (_e *MockIInitiation_Expecter) Persist(initn interface{}) *MockIInitiation_Persist_Call {
	return &MockIInitiation_Persist_Call{Call: _e.mock.On("Persist", initn)}
}

func (_c *MockIInitiation_Persist_Call) Run(run func(initn *data.Initiation)) *MockIInitiation_Persist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*data.Initiation))
	})
	return _c
}

func (_c *MockIInitiation_Persist_Call) Return(_a0 *data.Initiation, _a1 error) *MockIInitiation_Persist_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIInitiation_Persist_Call) RunAndReturn(run func(*data.Initiation) (*data.Initiation, error)) *MockIInitiation_Persist_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIInitiation creates a new instance of MockIInitiation. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIInitiation(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIInitiation {
	mock := &MockIInitiation{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
