// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	data "github.com/alanwade2001/go-sepa-portal/internal/data"
	mock "github.com/stretchr/testify/mock"
)

// IDocument is an autogenerated mock type for the IDocument type
type IDocument struct {
	mock.Mock
}

// InitiateDocument provides a mock function with given fields: content
func (_m *IDocument) InitiateDocument(content string) (*data.Initiation, error) {
	ret := _m.Called(content)

	if len(ret) == 0 {
		panic("no return value specified for InitiateDocument")
	}

	var r0 *data.Initiation
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*data.Initiation, error)); ok {
		return rf(content)
	}
	if rf, ok := ret.Get(0).(func(string) *data.Initiation); ok {
		r0 = rf(content)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*data.Initiation)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(content)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIDocument creates a new instance of IDocument. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIDocument(t interface {
	mock.TestingT
	Cleanup(func())
}) *IDocument {
	mock := &IDocument{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
