// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	model "github.com/alanwade2001/go-sepa-portal/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// IInitiationSM is an autogenerated mock type for the IInitiationSM type
type IInitiationSM struct {
	mock.Mock
}

// FireEvent provides a mock function with given fields: evt
func (_m *IInitiationSM) FireEvent(evt model.InitiationEvent) (string, error) {
	ret := _m.Called(evt)

	if len(ret) == 0 {
		panic("no return value specified for FireEvent")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(model.InitiationEvent) (string, error)); ok {
		return rf(evt)
	}
	if rf, ok := ret.Get(0).(func(model.InitiationEvent) string); ok {
		r0 = rf(evt)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(model.InitiationEvent) error); ok {
		r1 = rf(evt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIInitiationSM creates a new instance of IInitiationSM. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIInitiationSM(t interface {
	mock.TestingT
	Cleanup(func())
}) *IInitiationSM {
	mock := &IInitiationSM{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
