// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	model "github.com/alanwade2001/go-sepa-portal/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// IMessage is an autogenerated mock type for the IMessage type
type IMessage struct {
	mock.Mock
}

// Send provides a mock function with given fields: initn
func (_m *IMessage) Send(initn *model.Initiation) error {
	ret := _m.Called(initn)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Initiation) error); ok {
		r0 = rf(initn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIMessage creates a new instance of IMessage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIMessage(t interface {
	mock.TestingT
	Cleanup(func())
}) *IMessage {
	mock := &IMessage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
